name: Publish Workflow

on:
    push:
        tags:
            - '*'

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    code_checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup NODE
              uses: actions/setup-node@v2
              with:
                  node-version: '24'
            - name: Install dependencies
              run: npm ci
            - name: Check code format
              run: npm run format
            - name: Check linting rules
              run: npm run lint
            - name: Test source code
              run: npm run test
            - name: Test types integrity
              run: npm run type:check
    build_docs:
        runs-on: ubuntu-latest
        needs: code_checkout
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
            - name: Install dependencies
              run: npm ci
            - name: Build documentation
              run: npm run build:doc
            - name: Upload documentation
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./docs
    publish_package:
        needs: code_checkout
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  registry-url: https://registry.npmjs.org/
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Build documentation
              run: npm run build:doc
            - name: Publish to registry
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    deploy_pages:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build_docs
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
